domain_yml = """
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy
  - printer_problem
  - printer_problem_deny

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_is_it_plugged_in
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"
 
  utter_did_that_help:
  - text: "Did that help you?"
  
  utter_is_it_plugged_in:
   - text: "Is it plugged in boy?"
  
  utter_happy:
  - text: "Great carry on!"
  
  utter_disappointed:
  - text: "disappointing"
  
  utter_expalin:
  - text: "what exactly is wrong?"
  
  utter_lies:
  - text: "LIES!! out of my sight peasant"
   
  utter_goodbye:
  - text: "Bye"
"""
%store domain_yml > domain.yml

print("Done!")
